service: <your-service-name>
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- frontend/node_modules
- frontend/public
- frontend/semantic
- frontend/src
- frontend/package.json
- frontend/README.md
- frontend/semantic.json
- frontend/yarn.lock

handlers:
- url: /static
  static_dir: frontend/build/static

- url: /.+
  script: main.app

- url: /
  static_files: frontend/build/index.html
  upload: frontend/build/index.html

